## Launch and connect to an ipyparallel cluster

```
ipcluster start --profile=mpi -n 4
```

In [1]:
import ipyparallel as ipp
c = ipp.Client(profile='mpi')

In [2]:
%%px
from mpi4py import MPI
print(f"Hi, I'm rank %d." % MPI.COMM_WORLD.rank)

[stdout:0] Hi, I'm rank 0.
[stdout:1] Hi, I'm rank 1.
[stdout:2] Hi, I'm rank 2.
[stdout:3] Hi, I'm rank 3.


To enable MPI, users have two options. Either export the environment variable `DEVITO_MPI=1` or, programmatically:

In [3]:
%%px
from devito import configuration
configuration['mpi'] = True

In [4]:
%%px
from devito import Grid, Function, Eq, Operator 
grid = Grid(shape=(4, 4))
u = Function(name="u", grid=grid, space_order=2, time_order=0)

In [5]:
%%px
u.data

Out[0:22]: 
Data([[0., 0.],
      [0., 0.]], dtype=float32)

Out[1:22]: 
Data([[0., 0.],
      [0., 0.]], dtype=float32)

Out[2:22]: 
Data([[0., 0.],
      [0., 0.]], dtype=float32)

Out[3:22]: 
Data([[0., 0.],
      [0., 0.]], dtype=float32)

In [6]:
%%px
import numpy as np

In [7]:
%%px
shape = (4, 4)
a = np.arange(16).reshape(shape)
b = a[::-1, ::-1]

In [8]:
%%px
a

Out[0:25]: 
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Out[1:25]: 
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Out[2:25]: 
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Out[3:25]: 
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
%%px
b

Out[0:26]: 
array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

Out[1:26]: 
array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

Out[2:26]: 
array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

Out[3:26]: 
array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [10]:
%%px
u.data[:] = a

In [11]:
%%px
u.data

Out[0:28]: 
Data([[0., 1.],
      [4., 5.]], dtype=float32)

Out[1:28]: 
Data([[2., 3.],
      [6., 7.]], dtype=float32)

Out[2:28]: 
Data([[ 8.,  9.],
      [12., 13.]], dtype=float32)

Out[3:28]: 
Data([[10., 11.],
      [14., 15.]], dtype=float32)

In [12]:
%%px
u.data[3, 3]

Out[3:29]: 15.0

In [14]:
%%px
u.data[2:0:-1, 2:0:-1]

Out[0:31]: Data([[5.]], dtype=float32)

Out[1:31]: Data([[6.]], dtype=float32)

Out[2:31]: Data([[9.]], dtype=float32)

Out[3:31]: Data([[10.]], dtype=float32)

In [15]:
%%px
u.data[:, :]

Out[0:32]: 
Data([[0., 1.],
      [4., 5.]], dtype=float32)

Out[1:32]: 
Data([[2., 3.],
      [6., 7.]], dtype=float32)

Out[2:32]: 
Data([[ 8.,  9.],
      [12., 13.]], dtype=float32)

Out[3:32]: 
Data([[10., 11.],
      [14., 15.]], dtype=float32)

In [16]:
%%px
u.data[::-1, ::-1]

Out[0:33]: 
Data([[5., 4.],
      [1., 0.]], dtype=float32)

Out[1:33]: 
Data([[7., 6.],
      [3., 2.]], dtype=float32)

Out[2:33]: 
Data([[13., 12.],
      [ 9.,  8.]], dtype=float32)

Out[3:33]: 
Data([[15., 14.],
      [11., 10.]], dtype=float32)

In [17]:
%%px
u.data[3:1:-1, 3:1:-1]

Out[0:34]: Data([], shape=(0, 0), dtype=float32)

Out[1:34]: Data([], shape=(0, 2), dtype=float32)

Out[2:34]: Data([], shape=(2, 0), dtype=float32)

Out[3:34]: 
Data([[15., 14.],
      [11., 10.]], dtype=float32)